- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl013/crnl026799472.crnl013.obvilchartes13-1.xml
Dites-moi si les modifications sont conformes ou non :)
> modificiations conformes du crnl013

- data/crnl026799472/crnl003/__cts__.xml
- data/crnl026799472/crnl003/crnl026799472.crnl003.obvilchartes3-1.xml
- data/crnl026799472/crnl003/crnl026799472.crnl003.obvilchartes3-2.xml
> Validation ensemble fichier crnl003

- data/crnl026799472/crnl025/__cts__.xml
- data/crnl026799472/crnl025/crnl026799472.crnl025.obvilchartes25-1.xml
Regardez et dites-moi si c'est bon
> modifications à jour ?

- data/crnl026799472/crnl013b/crnl026799472.crnl013b.obvilchartes13b-1.xml
Regardez et dites moi si c'est bon !
> modifications conformes 13b

- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl023/crnl026799472.crnl023.obvilchartes23-1.xml
Ce fichier est voué à être le modèle pour nos modifications.
> mise à jour des fichiers crnl023, fait par tou.te.s, pour modèle

- data/crnl026799472/crnl002/__cts__.xml
- data/crnl026799472/crnl002/crnl026799472.crnl002.obvilchartes2-1.xml
> ajout crnl002

- data/crnl026799472/crnl006/__cts__.xml
- data/crnl026799472/crnl006/crnl026799472.crnl006.obvilchartes1-1.xml
fichiers à jour, regardez s'il vous plait !
> ajout fichiers crnl006

- data/crnl026799472/crnl005/__cts__.xml
> modifs dateSubmitted fichier cts 005

- data/crnl026799472/crnl012/__cts__.xml
- data/crnl026799472/crnl012/crnl026799472.crnl012.obvilchartes1-1.xml
@MyleneM c'est bon, tu peux vérifier ce fichier !
> ajout des fichiers crnl012

- data/crnl026799472/crnl015/__cts__.xml
- data/crnl026799472/crnl015/crnl026799472.crnl015.obvilchartes1-1.xml
@MyleneM c'est bon, tu peux vérifier ce fichier !
> ajout des fichiers crnl015

- data/crnl026799472/crnl029/__cts__.xml
- data/crnl026799472/crnl029/crnl026799472.crnl029.obvilchartes29-1.xml
> ajouts crnl029

- data/crnl026799472/crnl024/__cts__.xml
- data/crnl026799472/crnl024/crnl026799472.crnl024.obvilchartes1-1.xml
> ajout des fichiers crnl024

- data/crnl026799472/crnl030/__cts__.xml
- data/crnl026799472/crnl030/crnl026799472.crnl030.obvilchartes1-1.xml
c'est bon, tu peux vérifier @MyleneM
> ajout des fichiers crnl030

- data/crnl026799472/crnl016/__cts__.xml
- data/crnl026799472/crnl016/crnl026799472.crnl016.obvilchartes16-1.xml
nouvelles modifications pour 16 ! à vérifer !
> ajouts crnl016

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl013b/__cts__.xml
- data/crnl026799472/crnl016/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl029/__cts__.xml
- data/crnl026799472/crnl031/__cts__.xml
> Crnl031 aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
mise à jour du modèle avec déclaration xml
> Crnl023 aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl029/__cts__.xml
> Crnl0029 aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl029/__cts__.xml
> Crnl013 aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl013b/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl029/__cts__.xml
> Crnl013b aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl013b/__cts__.xml
- data/crnl026799472/crnl016/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
- data/crnl026799472/crnl029/__cts__.xml
> Crnl016 aj

- data/crnl026799472/crnl005/__cts__.xml
- data/crnl026799472/crnl013/__cts__.xml
- data/crnl026799472/crnl013b/__cts__.xml
- data/crnl026799472/crnl023/__cts__.xml
13b à jour avec modif xml:lang
> Crnl013baj

- data/crnl026799472/crnl005/__cts__.xml
> màj encore et encore 005

- data/crnl026799472/crnl013/__cts__.xml
petite modification : ajout accent circonflexe
¡ à relire avant de merger !
> modif 13 accent circonflexe

- data/crnl026799472/crnl025/__cts__.xml
on espère la dernière modif de 25
> denière modif 25

- data/crnl026799472/crnl006/__cts__.xml
- data/crnl026799472/crnl006/crnl026799472.crnl006.obvilchartes6-1.xml
> mise à jour des fichiers 006

- data/crnl026799472/crnl006/crnl026799472.crnl006.obvilchartes6-1.xml
- data/crnl026799472/crnl011/__cts__.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-1.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-2.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-3.xml
- data/crnl026799472/crnl012/__cts__.xml
- data/crnl026799472/crnl012/crnl026799472.crnl012.obvilchartes12-1.xml
- data/crnl026799472/crnl015/__cts__.xml
- data/crnl026799472/crnl015/crnl026799472.crnl015.obvilchartes15-1.xml
- data/crnl026799472/crnl024/__cts__.xml
- data/crnl026799472/crnl024/crnl026799472.crnl024.obvilchartes24-1.xml
- data/crnl026799472/crnl030/__cts__.xml
- data/crnl026799472/crnl030/crnl026799472.crnl030.obvilchartes30-1.xml
Voici mes fichiers à jour. Vérifiez et mergez si c'est bon !
> ajouts des fichiers à jour 6, 11, 12, 15, 24, 31

- data/crnl026799472/crnl012/crnl026799472.crnl012.obvilchartes12-1.xml
petites modifications de l'urn du @xml:base du text
> modifications urn du xml:base

- data/crnl026799472/crnl025/crnl026799472.crnl025.obvilchartes25-1.xml
> test 3 sur les pbs travis

- data/crnl026799472/crnl005/crnl026799472.crnl005.obvilchartes5-1.xml
- data/crnl026799472/crnl013/crnl026799472.crnl013.obvilchartes13-1.xml
- data/crnl026799472/crnl013b/crnl026799472.crnl013b.obvilchartes13b-1.xml
- data/crnl026799472/crnl016/crnl026799472.crnl016.obvilchartes16-1.xml
- data/crnl026799472/crnl029/crnl026799472.crnl029.obvilchartes29-1.xml
- data/crnl026799472/crnl031/crnl026799472.crnl031.obvilchartes31-1.xml
les modifications sur les fichiers tei de texte pour que ça passe travis. 
Modifications aussi de 005 qui avait échappé au renommage, etc !
> modifications des fichiers pour valid

- data/crnl026799472/crnl006/crnl026799472.crnl006.obvilchartes6-1.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-1.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-2.xml
- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-3.xml
- data/crnl026799472/crnl012/crnl026799472.crnl012.obvilchartes12-1.xml
- data/crnl026799472/crnl015/crnl026799472.crnl015.obvilchartes15-1.xml
- data/crnl026799472/crnl024/crnl026799472.crnl024.obvilchartes24-1.xml
- data/crnl026799472/crnl030/crnl026799472.crnl030.obvilchartes30-1.xml
Voici les modifications des fichiers TEI qui doivent réussir à passer Travis.
> modifications des fichiers conformes TEI

- data/crnl026799472/crnl011/crnl026799472.crnl011.obvilchartes11-3.xml
Voici le 11-3 ; on espère qu'il va passer cette fois...
> modifications du 11-3 qui devrait passer

- data/crnl026799472/crnl023/crnl026799472.crnl023.obvilchartes23-1.xml
> ajout de l'attribut xml:lang dans le 23 pour valid

- data/crnl026799472/crnl007/crnl026799472.crnl007.obvilchartes7-2.xml
> J'avais oublié la seconde édition de "Médée".
